"""изменение длины короткой ссылки

Revision ID: 2afcca0fdee8
Revises: 92d5dd079f47
Create Date: 2025-09-30 21:20:57.008407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afcca0fdee8'
down_revision = '92d5dd079f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
